version: "3.9"

services:
    bot:
        container_name: "bot"
        image: bot-test-docker
        environment:
            - BotToken=/run/secrets/BotToken
            - teaTimeId=/run/secrets/teaTimeId
            - ServerID=/run/secrets/ServerID
            - teaTimeChannel=/run/secrets/teaTimeChannel
        secrets:
          - BotToken
          - teaTimeId
          - ServerID
          - teaTimeChannel

secrets:
    BotToken:
        file: ./secrets/BotToken.txt
    teaTimeId:
        file: ./secrets/teaTimeId.txt
    ServerID:
        file: ./secrets/ServerID.txt
    teaTimeChannel:
        file: ./secrets/teaTimeChannel.txt