version: "3.9"

services:
    bot:
        container_name: "bot"
        image: bot-test-docker
        environment:
            - BotToken="Secret"
            - teaTimeId="Secret"
            - ServerID="Secret"
            - teaTimeChannel="Secret"
